# From https://medium.com/@adaml.poniatowski/installing-a-postgresql-operator-on-kubernetes-with-istio-and-longhorn-698eec2835c0
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-postgres
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fromBackup: ""
allowVolumeExpansion: true
---
kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "test-postgres"
  namespace: "default"
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "15"
  numberOfInstances: 3
  # enableMasterLoadBalancer: true
  # enableReplicaLoadBalancer: true
  volume:
    size: "10Gi"
    storageClass: "longhorn-postgres"
  users:
    test_user: []
  databases:
    test_user: test_user
  resources:
    requests:
      cpu: 1000m
      memory: 7Gi
    limits:
      cpu: 4000m
      memory: 8Gi
