baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Performance and usability analysis of virtual clusters in Kubernetes'
theme = ["github.com/dzello/reveal-hugo"]
relativeURLs = false
uglyURLs = true


[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
codeFences = false

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
custom_theme = "custom-theme.scss"
custom_theme_compile = true
slide_number = true
