name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: "Install Required Fonts"
        run: |
          curl -Lo merriweather.zip https://fonts.google.com/download?family=Merriweather
          unzip merriweather.zip -d /usr/share/fonts
          curl -Lo cascadiacode.zip https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.0/CascadiaCode.zip
          unzip cascadiacode.zip -d /usr/share/fonts
          fc-cache -fv


      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: thesis/main.typ

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        if: ${{ !env.ACT }}
        with:
          name: PDF
          path: thesis/main.pdf

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: main.pdf
